[[def]]
type = "Atlas"
id = "buildings"
dir = "./textures/buildings"
res_name = "buildings"

	[[def.variants]]
	name = "pixel"
	dimension = 16

	[[def.variants]]
	name = "simple"
	dimension = 64

	[[def.variants]]
	name = "fancy"
	dimension = 256

	[[def.variants]]
	name = "x-fancy"
	dimension = 1024

[[def]]
type = "Atlas"
id = "icons"
dir = "./textures/icons"
res_name = "icons"

	[[def.variants]]
	name = "simple"
	dimension = 16

	[[def.variants]]
	name = "fancy"
	dimension = 64

	[[def.variants]]
	name = "x-fancy"
	dimension = 256

[[def]]
type = "Atlas"
id = "vehicles"
dir = "./textures/vehicles"
res_name = "vehicles"

	[[def.variants]]
	name = "simple"
	dimension = 64

	[[def.variants]]
	name = "fancy"
	dimension = 256

	[[def.variants]]
	name = "x-fancy"
	dimension = 1024
