[[include]]
file = "buildings/core.toml"

[[include]]
file = "buildings/customs.toml"

[[include]]
file = "buildings/driving-school.toml"

[[include]]
file = "buildings/filtration-plant.toml"

[[include]]
file = "buildings/hut.toml"

[[include]]
file = "buildings/prison.toml"

[[include]]
file = "buildings/solar-panel.toml"

[[include]]
file = "buildings/stadium.toml"

[[include]]
file = "buildings/terminal.toml"

[[include]]
file = "buildings/vault.toml"

