[[def]]
type = "Cargo"
id = "amino-acid"
category = "raw-mineral"
name = {src = "main", key = "cargo-amino-acid"}
summary = {src = "main", key = "cargo-amino-acid.summary"}
description = {src = "main", key = "cargo-amino-acid.description"}
texture = {src = "icons", name = "amino-acid"}

[[def]]
type = "Cargo"
id = "rock"
category = "raw-mineral"
name = {src = "main", key = "cargo-rock"}
summary = {src = "main", key = "cargo-rock.summary"}
description = {src = "main", key = "cargo-rock.description"}
texture = {src = "icons", name = "rock"}

[[def]]
type = "Cargo"
id = "dna"
category = "organic"
name = {src = "main", key = "cargo-dna"}
summary = {src = "main", key = "cargo-dna.summary"}
description = {src = "main", key = "cargo-dna.description"}
texture = {src = "icons", name = "dna"}

[[def]]
type = "Cargo"
id = "pepples"
category = "ammunition"
name = {src = "main", key = "cargo-pepples"}
summary = {src = "main", key = "cargo-pepples.summary"}
description = {src = "main", key = "cargo-pepples.description"}
texture = {src = "icons", name = "pepples"}

[[def]]
type = "Cargo"
id = "sediment"
category = "junk"
name = {src = "main", key = "cargo-sediment"}
summary = {src = "main", key = "cargo-sediment.summary"}
description = {src = "main", key = "cargo-sediment.description"}
texture = {src = "icons", name = "sediment"}

[[def]]
type = "Cargo"
id = "aluminium"
category = "intermediate-material"
name = {src = "main", key = "cargo-aluminium"}
summary = {src = "main", key = "cargo-aluminium.summary"}
description = {src = "main", key = "cargo-aluminium.description"}
texture = {src = "icons", name = "aluminium"}

[[def]]
type = "Cargo"
id = "battery"
category = "container"
name = {src = "main", key = "cargo-battery"}
summary = {src = "main", key = "cargo-battery.summary"}
description = {src = "main", key = "cargo-battery.description"}
texture = {src = "icons", name = "battery"}

[[def]]
type = "Cargo"
id = "asteroidal-water-bottle"
category = "container"
name = {src = "main", key = "cargo-asteroidal-water-bottle"}
summary = {src = "main", key = "cargo-asteroidal-water-bottle.summary"}
description = {src = "main", key = "cargo-asteroidal-water-bottle.description"}
texture = {src = "icons", name = "asteroidal-water-liquid-bottle"}

[[def]]
type = "Cargo"
id = "filtered-water-bottle"
category = "container"
name = {src = "main", key = "cargo-filtered-water-bottle"}
summary = {src = "main", key = "cargo-filtered-water-bottle.summary"}
description = {src = "main", key = "cargo-filtered-water-bottle.description"}
texture = {src = "icons", name = "filtered-water-liquid-bottle"}

[[def]]
type = "Cargo"
id = "deionized-water-bottle"
category = "container"
name = {src = "main", key = "cargo-deionized-water-bottle"}
summary = {src = "main", key = "cargo-deionized-water-bottle.summary"}
description = {src = "main", key = "cargo-deionized-water-bottle.description"}
texture = {src = "icons", name = "deionized-water-liquid-bottle"}

[[def]]
type = "Cargo"
id = "urine-bottle"
category = "container"
name = {src = "main", key = "cargo-urine-bottle"}
summary = {src = "main", key = "cargo-urine-bottle.summary"}
description = {src = "main", key = "cargo-urine-bottle.description"}
texture = {src = "icons", name = "urine-liquid-bottle"}

[[def]]
type = "Cargo"
id = "coolant-bottle"
category = "container"
name = {src = "main", key = "cargo-coolant-bottle"}
summary = {src = "main", key = "cargo-coolant-bottle.summary"}
description = {src = "main", key = "cargo-coolant-bottle.description"}
texture = {src = "icons", name = "coolant-liquid-bottle"}

[[def]]
type = "Cargo"
id = "oxygen-bottle"
category = "container"
name = {src = "main", key = "cargo-oxygen-bottle"}
summary = {src = "main", key = "cargo-oxygen-bottle.summary"}
description = {src = "main", key = "cargo-oxygen-bottle.description"}
texture = {src = "icons", name = "oxygen-gas-bottle"}

[[def]]
type = "Cargo"
id = "carbon-dioxide-bottle"
category = "container"
name = {src = "main", key = "cargo-carbon-dioxide-bottle"}
summary = {src = "main", key = "cargo-carbon-dioxide-bottle.summary"}
description = {src = "main", key = "cargo-carbon-dioxide-bottle.description"}
texture = {src = "icons", name = "carbon-dioxide-gas-bottle"}

[[def]]
type = "Cargo"
id = "nitrogen-bottle"
category = "container"
name = {src = "main", key = "cargo-nitrogen-bottle"}
summary = {src = "main", key = "cargo-nitrogen-bottle.summary"}
description = {src = "main", key = "cargo-nitrogen-bottle.description"}
texture = {src = "icons", name = "nitrogen-gas-bottle"}
