cargo-amino-acid = Amino acid
cargo-amino-acid-summary = An organic mineral.
cargo-amino-acid-description = Amino acids are found in small amounts in asteroids. Use them to synthesize food and DNA.
cargo-rock = Rock
cargo-rock-summary = Chunks of rocks from asteroids.
cargo-rock-description = Rocks are the cheapest type of material obtained from asteroids. They can be used as ammunition or disposed as junk.
cargo-dna = DNA
cargo-dna-summary = Genetic material.
cargo-dna-description = DNA is used to produce inhabitants through asexual reproduction. Although morally challenged, this is the only way to start a new colony from scratch.
cargo-pepples = Pepples
cargo-pepples-summary = Stone pepples used as ammunition.
cargo-pepples-description = Pepples are produced by decomposing rocks.They are the basic type of ammunition for defense.
cargo-sediment = Sediment
cargo-sediment-summary = Filtration and distillation residue.
cargo-sediment-description = Sediments are waste produced during liquid processing. They cannot be used for anything, and should be ejected with junk launchers to avoid filling up storage space.
cargo-aluminium = Aluminium
cargo-aluminium-summary = A metal used for construction.
cargo-aluminium-description = A metal used for construction.
cargo-battery = Battery
cargo-battery-summary = Stores a small amount of power
cargo-battery-description = Charged in charging stations and discharged in discharging stations, batteries serve as an alternative method to transfer electricity between buildings. They are useful for avoiding construction of power cables into low-consumption regions and ensuring uninterrupted power supply in regions where cable often disconnects.
cargo-asteroidal-water-bottle = Liquid bottle (Asteroidal water)
cargo-asteroidal-water-bottle-summary = Stores a small amount of Asteroidal water
cargo-asteroidal-water-bottle-description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-filtered-water-bottle = Liquid bottle (Filtered water)
cargo-filtered-water-bottle-summary = Stores a small amount of Filtered water
cargo-filtered-water-bottle-description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-deionized-water-bottle = Liquid bottle (Deionized water)
cargo-deionized-water-bottle-summary = Stores a small amount of Deionized water
cargo-deionized-water-bottle-description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-urine-bottle = Liquid bottle (Urine)
cargo-urine-bottle-summary = Stores a small amount of Urine
cargo-urine-bottle-description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-coolant-bottle = Liquid bottle (Coolant)
cargo-coolant-bottle-summary = Stores a small amount of Coolant
cargo-coolant-bottle-description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-oxygen-bottle = Gas bottle (Oxygen)
cargo-oxygen-bottle-summary = Stores a small amount of Oxygen
cargo-oxygen-bottle-description = Produced in gas bottlers and centrifuges, gas bottles can be used to transfer a small amount of gas to factories as a replacement of diffusing gas slowly through corridors.
cargo-carbon-dioxide-bottle = Gas bottle (Carbon dioxide)
cargo-carbon-dioxide-bottle-summary = Stores a small amount of Carbon dioxide
cargo-carbon-dioxide-bottle-description = Produced in gas bottlers and centrifuges, gas bottles can be used to transfer a small amount of gas to factories as a replacement of diffusing gas slowly through corridors.
cargo-nitrogen-bottle = Gas bottle (Nitrogen)
cargo-nitrogen-bottle-summary = Stores a small amount of Nitrogen
cargo-nitrogen-bottle-description = Produced in gas bottlers and centrifuges, gas bottles can be used to transfer a small amount of gas to factories as a replacement of diffusing gas slowly through corridors.

cargo-cats-raw-mineral = Raw mineral
cargo-cats-raw-mineral-description = Raw minerals are obtained by receiving and decomposing incoming asteroids. Deflecting asteroids reduces the production of these minerals.
cargo-cats-organic = Organic
cargo-cats-organic-description = Organic cargo is used for inhabitant birth and survival.
cargo-cats-ammunition = Ammunition
cargo-cats-ammunition-description = Ammunition is ejected by defensive weapons to slow down or deflect asteroids.
cargo-cats-junk = Junk
cargo-cats-junk-description = Other forms of resources can be packaged as container cargo. This allows inhabitants to carry small amount of all resources to poorly developed regions.
cargo-cats-intermediate-material = Intermediate material
cargo-cats-intermediate-material-description = Intermediate materials are derived from raw minerals or other intermediate materials to feed into other factories. They cannot be used in utility facilities.
cargo-cats-container = Container
cargo-cats-container-description = Junk is the useless residue produced in other mechansims. They must be ejected out of the colony using junk launchers, otherwise they would fill up the space of the colony.

liquid-asteroidal-water = Asteroidal water
liquid-asteroidal-water-summary = Water found on asteroids
liquid-asteroidal-water-description = Deposits of water can sometimes be found in asteroids. Contaminated by asteroidal minerals, it must be filtered to be used in factories,\n            or deionized so that it is drinkable by inhabitants.
liquid-filtered-water = Filtered water
liquid-filtered-water-summary = Water without insoluble impurities.
liquid-filtered-water-description = Filtered water is removed of insoluble impurities, so they can be used in other factories without clogging up conduits.
liquid-deionized-water = Deionized water
liquid-deionized-water-summary = Drinking water
liquid-deionized-water-description = Soluble impurities in water are removed from water during deionization. This makes the water safe for inhabitant intake.
liquid-urine = Urine
liquid-urine-summary = Waste produced by inhabitants
liquid-urine-description = Urines are organic waste produced by inhabitants in houses. Arrange sewage pipes to remove them from houses and recycle them by distillation into drinking water.
liquid-coolant = Coolant
liquid-coolant-summary = A liquid at very low temperature
liquid-coolant-description = Coolants are produced by condensation of nitrogen. They are required in factories with highly exothermic reactions.
liquid-contaminated-liquid = Contaminated liquid
liquid-contaminated-liquid-summary = Unusable liquid
liquid-contaminated-liquid-description = A useless liquid caused by mixing different types of liquids. This liquid type cannot be used for anything, damaging most factories it flows into.

gas-oxygen = Oxygen
gas-oxygen-summary = Needed for breathing
gas-oxygen-description = Oxygen is required for survival of inhabitants. Inhabitants cannot work in buildings with low oxygen content, except for construction work, where sufficient oxygen must be available in adjacent buildings.
gas-carbon-dioxide = Carbon dioxide
gas-carbon-dioxide-summary = Photosynthesis material
gas-carbon-dioxide-description = Carbon dioxide is produced in houses and consumed in oxygen farms. While high carbon dioxide level is not necessarily fatal, they reduce the levels of other gases in the air.
gas-nitrogen = Nitrogen
gas-nitrogen-summary = An abundant, safe gas for pressure regulation
gas-nitrogen-description = Nitrogen is found in abundant amounts. Although chemically inactive, they are great for pressure regulation and can be condensed to produce coolants.

skill-age = Age
skill-age-description = Age of the inhabitant. Some jobs require operators of a specific age range. A high age increases the probability of health decrease.
skill-health = Health
skill-health-description = Physical well-being of the inhabitant. The inhabitant dies when health drops to zero.
skill-happiness = Happiness
skill-happiness-description = Inhabitants lose happiness when they work and gain happiness when they have entertainment.
skill-satisfaction = Satisfaction
skill-satisfaction-description = Inhabitants lose satisfaction when they do not receive sufficient supplies in their house. If satisfaction drops too low, inhabitants become outlaws and commit crimes.
skill-infamy = Infamy
skill-infamy-description = Inhabitants earn infamy when they perform crimes. Infamy values are used by security mechanisms to identify the crime threat of an inhabitant, such as movement control and police patrol. Inhabitants can lose infamy by imprisonment.
skill-morality = Morality
skill-morality-description = Inhabitants are educated with morality values to reduce the probability of committing crimes.
skill-athletic-skill = Athletic skill
skill-athletic-skill-description = Inhabitants with good athletic skill can walk faster outside a vehicle.
skill-driving-skill = Driving skill
skill-driving-skill-description = When an inhabitant with good driving skill operates a vehicle, it can move faster across rails.
skill-mechanic-skill = Mechanic skill
skill-mechanic-skill-description = Inhabitants are trained as mechanics to operate factories more effectively.
skill-construction-skill = Construction skill
skill-construction-skill-description = Inhabitants are trained as builders to construct new buildings faster.
skill-teaching-skill = Teaching skill
skill-teaching-skill-description = Inhabitants are trained as teachers so that the next generation can learn better in schools.
skill-military-skill = Military skill
skill-military-skill-description = Inhabitants are trained as soldiers or police. Weapons they operate will be more effective, and they have higher chance of successfully arresting an outlaw.

vehicle-raptor = Raptor
vehicle-raptor-description = A fast, lightweight vehicle.
vehicle-freighter = Freighter
vehicle-freighter-description = A slow vehicle used to carry large amounts of cargo
vehicle-bus = Bus
vehicle-bus-description = A slow vehicle used to carry many passengers

building-core = Core
building-core-summary = The center of the whole colony
building-core-description = The core is the ultimate building to protect. It provides basic resources, including a small amount of uninterrupted power, some oxygen generation and a few population housing. Destruction of the core ends the game.
building-hut = Hut
building-hut-summary = A small living quarter.
building-hut-description = ""
building-terminal = Terminal
building-terminal-summary = Connects and drives corridors
building-terminal-description = ""
building-solar-panel = Solar panel
building-solar-panel-summary = Basic power production
building-solar-panel-description = Solar power is an effective power generation mechanism. Unobstructed by planetary atmosphere, solar panels are the primary source of power in early to mid game.
building-vault = Vault
building-vault-summary = Store lots of cargo
building-vault-description = Large amounts of cargo can be stored here for future use. This can also be used as a temporary junkyard if junk launchers cannot catch up quickly enough.
building-filtration-plant = Filtration plant
building-filtration-plant-summary = Filter insoluble impurities from water
building-filtration-plant-description = Asteroidal water is often mixed with different sorts of junk. These solid impurities will clog and damage conduits if passed directly. A filtration plant can separate the solid junk from the water.\n\nAlthough filtered water is still not edible for inhabitants, it demonstrates most of the physical properties of water, such as the high heat capacity and low viscosity. Therefore, filtered water is sufficient for most industrial uses.
building-driving-school = Driving school
building-driving-school-summary = Train inhabitants to drive better
building-driving-school-description = Train inhabitants to drive better.
building-stadium = Stadium
building-stadium-summary = Inhabitants can exercise here
building-stadium-description = Inhabitants do exercise here, recovering happiness and improve athletic skills.
building-prison = Prison
building-prison-summary = Correctional services for criminals
building-prison-description = Inhabitants with negative satisfaction are imprisoned here to recultivate morality and restore satisfaction.
building-customs = Customs
building-customs-summary = Disallow outlaws from intrusion
building-customs-description = Customs is a security checkpoint at which operators check all inhabitants passing through. Surround important buildings with customs so that outlaws cannot grief them.

building-cats-population = Population
building-cats-population-description = Buildings to support inhabitant population
building-cats-traffic = Traffic
building-cats-traffic-description = Buildings for traffic control
building-cats-electricity = Electricity
building-cats-electricity-description = Buildings to manage electricity
building-cats-storage = Storage
building-cats-storage-description = Buildings to store resources
building-cats-industrial = Industrial
building-cats-industrial-description = Buildings for processing intermediates
building-cats-education = Education
building-cats-education-description = Buildings to train inhabitant skills
building-cats-entertainment = Entertainment
building-cats-entertainment-description = Buildings to restore happiness
building-cats-security = Security
building-cats-security-description = Buildings related to crimes

storage-liquid-generic-reservoir = Reservoir
storage-liquid-generic-buffer = Buffer
storage-liquid-factory-input = Input
storage-liquid-factory-output = Output
storage-liquid-housing-drinking = Drinking
storage-liquid-housing-toilet = Toilet

storage-population-generic-transit = Transit
storage-population-generic-operator = Operator
storage-population-generic-user = User
storage-population-school-teacher = Teacher
storage-population-school-student = Student
storage-population-housing-housing = Housing
storage-population-prison-prisoner = Prisoner
storage-population-prison-guard = Guard

reaction-solar-power = Solar power
reaction-solar-power-description = Generates electricity from sunlight.
reaction-asteroidal-water-filtration = Asteroidal water filtration
reaction-asteroidal-water-filtration-description = Filters out rocks and other sediments in asteroidal water.
reaction-driving-lesson = Driving lesson
reaction-driving-lesson-description = Assign an experienced driver to teach driving skills to other inhabitants.
reaction-imprisonment = Imprisonment
reaction-imprisonment-description = Imprison criminals to recultivate their moral values and turn to a good citizen.
reaction-stadium = Stadium
reaction-stadium-description = Inhabitants can improve athletic skills slowly but gain happiness.
reaction-correctional-service = Correctional service
reaction-correctional-service-description = ""

crime-pickpocket = Pickpocket
crime-pickpocket-description = Steal cargo carried by other inhabitants
crime-robbery = Robbery
crime-robbery-description = Rob a building and remove the cargo stored inside
crime-arson = Arson
crime-arson-description = Set a building on fire
