[[def]]
type = "Liquid"
id = "asteroidal-water"
viscosity = 1.0
name = {src = "main", key = "liquid.asteroidal-water"}
summary = {src = "main", key = "liquid.asteroidal-water.summary"}
description = {src = "main", key = "liquid.asteroidal-water.description"}
texture = {src = "icons", name = "asteroidal-water"}

[[def]]
type = "Liquid"
id = "filtered-water"
viscosity = 1.0
name = {src = "main", key = "liquid.filtered-water"}
summary = {src = "main", key = "liquid.filtered-water.summary"}
description = {src = "main", key = "liquid.filtered-water.description"}
texture = {src = "icons", name = "filtered-water"}

[[def]]
type = "Liquid"
id = "deionized-water"
viscosity = 1.0
name = {src = "main", key = "liquid.deionized-water"}
summary = {src = "main", key = "liquid.deionized-water.summary"}
description = {src = "main", key = "liquid.deionized-water.description"}
texture = {src = "icons", name = "deionized-water"}

[[def]]
type = "Liquid"
id = "urine"
viscosity = 5.0
name = {src = "main", key = "liquid.urine"}
summary = {src = "main", key = "liquid.urine.summary"}
description = {src = "main", key = "liquid.urine.description"}
texture = {src = "icons", name = "urine"}

[[def]]
type = "Liquid"
id = "coolant"
viscosity = 1.0
name = {src = "main", key = "liquid.coolant"}
summary = {src = "main", key = "liquid.coolant.summary"}
description = {src = "main", key = "liquid.coolant.description"}
texture = {src = "icons", name = "coolant"}

[[def]]
type = "Liquid"
id = "contaminated-liquid"
viscosity = 2.0
name = {src = "main", key = "liquid.contaminated-liquid"}
summary = {src = "main", key = "liquid.contaminated-liquid.summary"}
description = {src = "main", key = "liquid.contaminated-liquid.description"}
texture = {src = "icons", name = "contaminated-liquid"}
