[scenario]
name = "Vanilla"
description = "The default game rules and minimal setup."

[config]
sun_speed = 0.0020943951
negligible_volume = 1.0

[[include]]
file = "./cargo/ALL.toml"

[[include]]
file = "./liquid/ALL.toml"

[[include]]
file = "./gas/ALL.toml"

[[include]]
file = "./skill/ALL.toml"

[[include]]
file = "./vehicle/ALL.toml"

[[include]]
file = "./building/ALL.toml"
