version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "P: Dependabot"
    - "P: Rust"
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "P: Dependabot"
    - "P: JavaScript"
- package-ecosystem: pip
  directory: "/client/textures"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "P: Dependabot"
    - "P: Python"
