[[def]]
type = "Liquid"
id = "asteroidal-water"
viscosity = 1.0
name = {src = "liquid", key = "asteroidal-water"}
summary = {src = "liquid", key = "asteroidal-water-summary"}
description = {src = "liquid", key = "asteroidal-water-description"}
texture = {src = "liquid", name = "asteroidal-water"}

[[def]]
type = "Cargo"
id = "asteroidal-water-bottle"
category = "container"
name = {src = "liquid", key = "asteroidal-water-bottle"}
summary = {src = "liquid", key = "asteroidal-water-bottle-summary"}
description = {src = "liquid", key = "asteroidal-water-bottle-description"}
texture = {src = "liquid", name = "asteroidal-water-bottle"}

[[def]]
type = "Liquid"
id = "filtered-water"
viscosity = 1.0
name = {src = "liquid", key = "filtered-water"}
summary = {src = "liquid", key = "filtered-water-summary"}
description = {src = "liquid", key = "filtered-water-description"}
texture = {src = "liquid", name = "filtered-water"}

[[def]]
type = "Cargo"
id = "filtered-water-bottle"
category = "container"
name = {src = "liquid", key = "filtered-water-bottle"}
summary = {src = "liquid", key = "filtered-water-bottle-summary"}
description = {src = "liquid", key = "filtered-water-bottle-description"}
texture = {src = "liquid", name = "filtered-water-bottle"}

[[def]]
type = "Liquid"
id = "deionized-water"
viscosity = 1.0
name = {src = "liquid", key = "deionized-water"}
summary = {src = "liquid", key = "deionized-water-summary"}
description = {src = "liquid", key = "deionized-water-description"}
texture = {src = "liquid", name = "deionized-water"}

[[def]]
type = "Cargo"
id = "deionized-water"
category = "container"
name = {src = "liquid", key = "deionized-water-bottle"}
summary = {src = "liquid", key = "deionized-water-bottle-summary"}
description = {src = "liquid", key = "deionized-water-bottle-description"}
texture = {src = "liquid", name = "deionized-water-bottle"}

[[def]]
type = "Liquid"
id = "urine"
viscosity = 5.0
name = {src = "liquid", key = "urine"}
summary = {src = "liquid", key = "urine-summary"}
description = {src = "liquid", key = "urine-description"}
texture = {src = "liquid", name = "urine"}

[[def]]
type = "Cargo"
id = "urine"
category = "container"
name = {src = "liquid", key = "urine-bottle"}
summary = {src = "liquid", key = "urine-bottle-summary"}
description = {src = "liquid", key = "urine-bottle-description"}
texture = {src = "liquid", name = "urine-bottle"}

[[def]]
type = "Liquid"
id = "coolant"
viscosity = 1.0
name = {src = "liquid", key = "coolant"}
summary = {src = "liquid", key = "coolant-summary"}
description = {src = "liquid", key = "coolant-description"}
texture = {src = "liquid", name = "coolant"}

[[def]]
type = "Cargo"
id = "coolant"
category = "container"
name = {src = "liquid", key = "coolant-bottle"}
summary = {src = "liquid", key = "coolant-bottle-summary"}
description = {src = "liquid", key = "coolant-bottle-description"}
texture = {src = "liquid", name = "coolant-bottle"}

[[def]]
type = "Liquid"
id = "contaminated-liquid"
viscosity = 2.0
name = {src = "liquid", key = "contaminated-liquid"}
summary = {src = "liquid", key = "contaminated-liquid-summary"}
description = {src = "liquid", key = "contaminated-liquid-description"}
texture = {src = "liquid", name = "contaminated-liquid"}

[[def]]
type = "Cargo"
id = "contaminated-liquid"
category = "container"
name = {src = "liquid", key = "contaminated-liquid-bottle"}
summary = {src = "liquid", key = "contaminated-liquid-bottle-summary"}
description = {src = "liquid", key = "contaminated-liquid-bottle-description"}
texture = {src = "liquid", name = "contaminated-liquid-bottle"}
