[[def]]
type = "CargoCategory"
id = "raw-mineral"
title = {src = "cargo-category", key = "raw-mineral"}
description = {src = "cargo-category", key = "raw-mineral-description"}

[[def]]
type = "CargoCategory"
id = "organic"
title = {src = "cargo-category", key = "organic"}
description = {src = "cargo-category", key = "organic-description"}

[[def]]
type = "CargoCategory"
id = "ammunition"
title = {src = "cargo-category", key = "ammunition"}
description = {src = "cargo-category", key = "ammunition-description"}

[[def]]
type = "CargoCategory"
id = "junk"
title = {src = "cargo-category", key = "junk"}
description = {src = "cargo-category", key = "junk-description"}

[[def]]
type = "CargoCategory"
id = "intermediate-material"
title = {src = "cargo-category", key = "intermediate-material"}
description = {src = "cargo-category", key = "intermediate-material-description"}

[[def]]
type = "CargoCategory"
id = "container"

title = {src = "cargo-category", key = "container"}
description = {src = "cargo-category", key = "container-description"}
