[[def]]
type = "Cargo"
id = "amino-acid"
category = "raw-mineral"
name = {src = "cargo", key = "amino-acid"}
summary = {src = "cargo", key = "amino-acid-summary"}
description = {src = "cargo", key = "amino-acid-description"}
texture = {src = "cargo", name = "amino-acid"}

[[def]]
type = "Cargo"
id = "rock"
category = "raw-mineral"
name = {src = "cargo", key = "rock"}
summary = {src = "cargo", key = "rock-summary"}
description = {src = "cargo", key = "rock-description"}
texture = {src = "cargo", name = "rock"}

[[def]]
type = "Cargo"
id = "dna"
category = "organic"
name = {src = "cargo", key = "dna"}
summary = {src = "cargo", key = "dna-summary"}
description = {src = "cargo", key = "dna-description"}
texture = {src = "cargo", name = "dna"}

[[def]]
type = "Cargo"
id = "pebbles"
category = "ammunition"
name = {src = "cargo", key = "pebbles"}
summary = {src = "cargo", key = "pebbles-summary"}
description = {src = "cargo", key = "pebbles-description"}
texture = {src = "cargo", name = "pebbles"}

[[def]]
type = "Cargo"
id = "sediment"
category = "junk"
name = {src = "cargo", key = "sediment"}
summary = {src = "cargo", key = "sediment-summary"}
description = {src = "cargo", key = "sediment-description"}
texture = {src = "cargo", name = "sediment"}

[[def]]
type = "Cargo"
id = "aluminium"
category = "intermediate-material"
name = {src = "cargo", key = "aluminium"}
summary = {src = "cargo", key = "aluminium-summary"}
description = {src = "cargo", key = "aluminium-description"}
texture = {src = "cargo", name = "aluminium"}

[[def]]
type = "Cargo"
id = "battery"
category = "container"
name = {src = "cargo", key = "battery"}
summary = {src = "cargo", key = "battery-summary"}
description = {src = "cargo", key = "battery-description"}
texture = {src = "cargo", name = "battery"}
