[[def]]
type = "LangBundle"
id = "cargo"

	[def.languages]
	en = "./lang/cargo/en.ftl"

[[def]]
type = "LangBundle"
id = "cargo-category"

	[def.languages]
	en = "./lang/category/en.ftl"

[[def]]
type = "Atlas"
id = "cargo"
dir = "./texture"

	[[def.variants]]
	name = "simple"
	dimension = 16

	[[def.variants]]
	name = "fancy"
	dimension = 64

	[[def.variants]]
	name = "x-fancy"
	dimension = 256

