[package]
name = "traffloat-graph"
description = "Traffloat structural graph management"
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}
repository = {workspace = true}
authors = {workspace = true}
version = {workspace = true}
rust-version = {workspace = true}

[dependencies]
bevy = {workspace = true}
typed-builder = "0.18.2"

[lints]
workspace = true
