[[def]]
type = "Gas"
id = "oxygen"
name = {src = "gas", key = "oxygen"}
summary = {src = "gas", key = "oxygen-summary"}
description = {src = "gas", key = "oxygen-description"}
texture = {src = "gas", name = "oxygen"}

[[def]]
type = "Cargo"
id = "oxygen"
category = "container"
name = {src = "gas", key = "oxygen-bottle"}
summary = {src = "gas", key = "oxygen-bottle-summary"}
description = {src = "gas", key = "oxygen-bottle-description"}
texture = {src = "gas", name = "oxygen-bottle"}

[[def]]
type = "Gas"
id = "carbon-dioxide"
name = {src = "gas", key = "carbon-dioxide"}
summary = {src = "gas", key = "carbon-dioxide-summary"}
description = {src = "gas", key = "carbon-dioxide-description"}
texture = {src = "gas", name = "carbon-dioxide"}

[[def]]
type = "Cargo"
id = "carbon-dioxide"
category = "container"
name = {src = "gas", key = "carbon-dioxide-bottle"}
summary = {src = "gas", key = "carbon-dioxide-bottle-summary"}
description = {src = "gas", key = "carbon-dioxide-bottle-description"}
texture = {src = "gas", name = "carbon-dioxide-bottle"}

[[def]]
type = "Gas"
id = "nitrogen"
name = {src = "gas", key = "nitrogen"}
summary = {src = "gas", key = "nitrogen-summary"}
description = {src = "gas", key = "nitrogen-description"}
texture = {src = "gas", name = "nitrogen"}

[[def]]
type = "Cargo"
id = "nitrogen"
category = "container"
name = {src = "gas", key = "nitrogen-bottle"}
summary = {src = "gas", key = "nitrogen-bottle-summary"}
description = {src = "gas", key = "nitrogen-bottle-description"}
texture = {src = "gas", name = "nitrogen-bottle"}
