[[def]]
type = "BuildingCategory"
id = "population"
title = {src = "building-category", key = "population"}
description = {src = "building-category", key = "population-description"}

[[def]]
type = "BuildingCategory"
id = "traffic"
title = {src = "building-category", key = "traffic"}
description = {src = "building-category", key = "traffic-description"}


[[def]]
type = "BuildingCategory"
id = "electricity"
title = {src = "building-category", key = "electricity"}
description = {src = "building-category", key = "electricity-description"}

[[def]]
type = "BuildingCategory"
id = "storage"
title = {src = "building-category", key = "storage"}
description = {src = "building-category", key = "storage-description"}

[[def]]
type = "BuildingCategory"
id = "industrial"
title = {src = "building-category", key = "industrial"}
description = {src = "building-category", key = "industrial-description"}

[[def]]
type = "BuildingCategory"
id = "education"
title = {src = "building-category", key = "education"}
description = {src = "building-category", key = "education-description"}

[[def]]
type = "BuildingCategory"
id = "entertainment"
title = {src = "building-category", key = "entertainment"}
description = {src = "building-category", key = "entertainment-description"}

[[def]]
type = "BuildingCategory"
id = "security"
title = {src = "building-category", key = "security"}
description = {src = "building-category", key = "security-description"}
