[[def]]
type = "Building"
id = "customs"
category = "security"
hitpoint = 300.0
name = {src = "building", key = "customs"}
summary = {src = "building", key = "customs-summary"}
description = {src = "building", key = "customs-description"}

	[[def.shapes]]
	unit = "Cube"
	texture = {src = "buildings", name = "customs"}

	[def.storage]
	cargo = 1000.0
	gas = 1000.0

		[[def.storage.liquid]]
		id = "buffer0"
		capacity = 10.0
		name = {src = "storage-liquid", key = "generic-buffer"}

		[[def.storage.liquid]]
		id = "buffer1"
		capacity = 10.0
		name = {src = "storage-liquid", key = "generic-buffer"}

		[[def.storage.population]]
		id = "operator"
		capacity = 2
		name = {src = "storage-population", key = "generic-operator"}

	[[def.features]]
	type = "SecureEntry"
	breach_probability = 0.001

		[[def.features.deny_if]]
		type = "AtLeast"
		skill = "infamy"
		level = 10.0

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Skill"
			ty = "military-skill"
			levels = {start = 0.0, end = 20.0}
			storage = "guard"

			[def.features.catalysts.multipliers]
			underflow = 1.0
			min = 1.0
			max = 0.01
			overflow = 0.01
