[[def]]
type = "LangBundle"
id = "building"

	[def.languages]
	en = "./lang/building/en.ftl"

[[def]]
type = "LangBundle"
id = "building-category"

	[def.languages]
	en = "./lang/category/en.ftl"

[[def]]
type = "LangBundle"
id = "storage-liquid"

	[def.languages]
	en = "./lang/storage/liquid/en.ftl"

[[def]]
type = "LangBundle"
id = "storage-population"

	[def.languages]
	en = "./lang/storage/population/en.ftl"

[[def]]
type = "LangBundle"
id = "reaction"

	[def.languages]
	en = "./lang/reaction/en.ftl"

[[def]]
type = "Atlas"
id = "buildings"
dir = "./texture"

	[[def.variants]]
	name = "pixel"
	dimension = 16

	[[def.variants]]
	name = "simple"
	dimension = 64

	[[def.variants]]
	name = "fancy"
	dimension = 256

	[[def.variants]]
	name = "x-fancy"
	dimension = 1024

