[[def]]
type = "Building"
id = "solar-panel"
category = "electricity"
hitpoint = 200.0
name = {src = "building", key = "solar-panel"}
summary = {src = "building", key = "solar-panel-summary"}
description = {src = "building", key = "solar-panel-description"}

	[[def.shapes]]
	unit = "Cube"
	texture = {src = "buildings", name = "solar-panel"}

	[def.storage]
	cargo = 1000.0
	gas = 1000.0

		[[def.storage.population]]
		id = "operator"
		capacity = 1
		name = {src = "storage-population", key = "generic-operator"}

	[[def.features]]
	type = "Reaction"
	title = {src = "reaction", key = "solar-power"}
	description = {src = "reaction", key = "solar-power-description"}

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Light"
			levels = {start = 0.0, end = 10.0}

			[def.features.catalysts.multipliers]
			underflow = 0.0
			min = 0.0
			max = 1.0
			overflow = 1.0

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Skill"
			ty = "mechanic-skill"
			storage = "operator"
			levels = {start = 0.0, end = 10.0}

			[def.features.catalysts.multipliers]
			underflow = 1.0
			min = 1.0
			max = 2.0
			overflow = 2.0

		[[def.features.puts]]
		type = "Electricity"
		base = 100.0

		[def.features.policy]
		configurable = true
		on_underflow = {type = "ReduceRate"}
		on_overflow = {type = "ReduceRate"}
