cargo-amino-acid = Amino acid
	.summary = An organic mineral.
	.description = Amino acids are found in small amounts in asteroids. Use them to synthesize food and DNA.
cargo-rock = Rock
    .summary = Chunks of rocks from asteroids.
    .description = Rocks are the cheapest type of material obtained from asteroids. They can be used as ammunition or disposed as junk.
cargo-dna = DNA
    .summary = Genetic material.
    .description = DNA is used to produce inhabitants through asexual reproduction. Although morally challenged, this is the only way to start a new colony from scratch.
cargo-pepples = Pepples
    .summary = Stone pepples used as ammunition.
    .description = Pepples are produced by decomposing rocks.They are the basic type of ammunition for defense.
cargo-sediment = Sediment
    .summary = Filtration and distillation residue.
    .description = Sediments are waste produced during liquid processing. They cannot be used for anything, and should be ejected with junk launchers to avoid filling up storage space.
cargo-aluminium = Aluminium
    .summary = A metal used for construction.
    .description = A metal used for construction.
cargo-battery = Battery
    .summary = Stores a small amount of power
    .description = Charged in charging stations and discharged in discharging stations, batteries serve as an alternative method to transfer electricity between buildings. They are useful for avoiding construction of power cables into low-consumption regions and ensuring uninterrupted power supply in regions where cable often disconnects.
cargo-asteroidal-water-bottle = Liquid bottle (Asteroidal water)
    .summary = Stores a small amount of Asteroidal water
    .description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-filtered-water-bottle = Liquid bottle (Filtered water)
    .summary = Stores a small amount of Filtered water
    .description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-deionized-water-bottle = Liquid bottle (Deionized water)
    .summary = Stores a small amount of Deionized water
    .description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-urine-bottle = Liquid bottle (Urine)
    .summary = Stores a small amount of Urine
    .description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-coolant-bottle = Liquid bottle (Coolant)
    .summary = Stores a small amount of Coolant
    .description = Produced in liquid bottlers and centrifuges, liquid bottles can be used to transfer a small amount of liquid to factories as a replacement of constructing dedicated pipes through corridors.
cargo-oxygen-bottle = Gas bottle (Oxygen)
    .summary = Stores a small amount of Oxygen
    .description = Produced in gas bottlers and centrifuges, gas bottles can be used to transfer a small amount of gas to factories as a replacement of diffusing gas slowly through corridors.
cargo-carbon-dioxide-bottle = Gas bottle (Carbon dioxide)
    .summary = Stores a small amount of Carbon dioxide
    .description = Produced in gas bottlers and centrifuges, gas bottles can be used to transfer a small amount of gas to factories as a replacement of diffusing gas slowly through corridors.
cargo-nitrogen-bottle = Gas bottle (Nitrogen)
    .summary = Stores a small amount of Nitrogen
    .description = Produced in gas bottlers and centrifuges, gas bottles can be used to transfer a small amount of gas to factories as a replacement of diffusing gas slowly through corridors.

cargo-cats-raw-mineral = Raw mineral
    .description = Raw minerals are obtained by receiving and decomposing incoming asteroids. Deflecting asteroids reduces the production of these minerals.
cargo-cats-organic = Organic
    .description = Organic cargo is used for inhabitant birth and survival.
cargo-cats-ammunition = Ammunition
    .description = Ammunition is ejected by defensive weapons to slow down or deflect asteroids.
cargo-cats-junk = Junk
    .description = Other forms of resources can be packaged as container cargo. This allows inhabitants to carry small amount of all resources to poorly developed regions.
cargo-cats-intermediate-material = Intermediate material
    .description = Intermediate materials are derived from raw minerals or other intermediate materials to feed into other factories. They cannot be used in utility facilities.
cargo-cats-container = Container
    .description = Junk is the useless residue produced in other mechansims. They must be ejected out of the colony using junk launchers, otherwise they would fill up the space of the colony.

liquid-asteroidal-water = Asteroidal water
    .summary = Water found on asteroids
    .description = "Deposits of water can sometimes be found in asteroids. Contaminated by asteroidal minerals, it must be filtered to be used in factories,\n            or deionized so that it is drinkable by inhabitants."
liquid-filtered-water = Filtered water
    .summary = Water without insoluble impurities.
    .description = "Filtered water is removed of insoluble impurities, so they can be used in other factories without clogging up conduits."
liquid-deionized-water = Deionized water
    .summary = Drinking water
    .description = Soluble impurities in water are removed from water during deionization. This makes the water safe for inhabitant intake.
liquid-urine = Urine
    .summary = Waste produced by inhabitants
    .description = Urines are organic waste produced by inhabitants in houses. Arrange sewage pipes to remove them from houses and recycle them by distillation into drinking water.
liquid-coolant = Coolant
    .summary = A liquid at very low temperature
    .description = Coolants are produced by condensation of nitrogen. They are required in factories with highly exothermic reactions.
liquid-contaminated-liquid = Contaminated liquid
    .summary = Unusable liquid
    .description = A useless liquid caused by mixing different types of liquids. This liquid type cannot be used for anything, damaging most factories it flows into.

gas-oxygen = Oxygen
    .summary = Needed for breathing
    .description = "Oxygen is required for survival of inhabitants. Inhabitants cannot work in buildings with low oxygen content, except for construction work, where sufficient oxygen must be available in adjacent buildings."
gas-carbon.dioxide = Carbon dioxide
    .summary = Photosynthesis material
    .description = "Carbon dioxide is produced in houses and consumed in oxygen farms. While high carbon dioxide level is not necessarily fatal, they reduce the levels of other gases in the air."
gas-nitrogen = Nitrogen
    .summary = "An abundant, safe gas for pressure regulation"
    .description = "Nitrogen is found in abundant amounts. Although chemically inactive, they are great for pressure regulation and can be condensed to produce coolants."

skill-age = Age
    .description = Age of the inhabitant. Some jobs require operators of a specific age range. A high age increases the probability of health decrease.
skill-health = Health
    .description = Physical well-being of the inhabitant. The inhabitant dies when health drops to zero.
skill-happiness = Happiness
    .description = Inhabitants lose happiness when they work and gain happiness when they have entertainment.
skill-satisfaction = Satisfaction
    .description = "Inhabitants lose satisfaction when they do not receive sufficient supplies in their house. If satisfaction drops too low, inhabitants become outlaws and commit crimes."
skill-infamy = Infamy
    .description = "Inhabitants earn infamy when they perform crimes. Infamy values are used by security mechanisms to identify the crime threat of an inhabitant, such as movement control and police patrol. Inhabitants can lose infamy by imprisonment."
skill-morality = Morality
    .description = Inhabitants are educated with morality values to reduce the probability of committing crimes.
skill-athletic-skill = Athletic skill
    .description = Inhabitants with good athletic skill can walk faster outside a vehicle.
skill-driving-skill = Driving skill
    .description = "When an inhabitant with good driving skill operates a vehicle, it can move faster across rails."
skill-mechanic-skill = Mechanic skill
    .description = Inhabitants are trained as mechanics to operate factories more effectively.
skill-construction-skill = Construction skill
    .description = Inhabitants are trained as builders to construct new buildings faster.
skill-teaching-skill = Teaching skill
    .description = Inhabitants are trained as teachers so that the next generation can learn better in schools.
skill-military-skill = Military skill
    .description = "Inhabitants are trained as soldiers or police. Weapons they operate will be more effective, and they have higher chance of successfully arresting an outlaw."

vehicle-raptor = Raptor
    .description = "A fast, lightweight vehicle."
vehicle-freighter = Freighter
    .description = A slow vehicle used to carry large amounts of cargo
vehicle-bus = Bus
    .description = A slow vehicle used to carry many passengers

reaction-solar-power = Solar power
    .description = "Generates electricity from sunlight."
reaction-asteroidal-water-filtration = Asteroidal water filtration
    .description = Filters out rocks and other sediments in asteroidal water.
reaction-driving-lesson = Driving lesson
    .description = Assign an experienced driver to teach driving skills to other inhabitants.
reaction-imprisonment = Imprisonment
    .description = Imprison criminals to recultivate their moral values and turn to a good citizen.
reaction-stadium = Stadium
    .description = Inhabitants can improve athletic skills slowly but gain happiness.

building-core = Core
    .summary = The center of the whole colony
    .description = "The core is the ultimate building to protect. It provides basic resources, including a small amount of uninterrupted power, some oxygen generation and a few population housing. Destruction of the core ends the game."
building-hut = Hut
    .summary = A small living quarter.
    .description = ""
building-terminal = Terminal
    .summary = Connects and drives corridors
    .description = ""
building-solar-panel = Solar panel
    .summary = Basic power production
    .description = "Solar power is an effective power generation mechanism. Unobstructed by planetary atmosphere, solar panels are the primary source of power in early to mid game."
building-vault = Vault
    .summary = Store lots of cargo
    .description = Large amounts of cargo can be stored here for future use. This can also be used as a temporary junkyard if junk launchers cannot catch up quickly enough.
building-filtration-plant = Filtration plant
    .summary = Filter insoluble impurities from water
    .description = "Asteroidal water is often mixed with different sorts of junk. These solid impurities will clog and damage conduits if passed directly. A filtration plant can separate the solid junk from the water.\n\nAlthough filtered water is still not edible for inhabitants, it demonstrates most of the physical properties of water, such as the high heat capacity and low viscosity. Therefore, filtered water is sufficient for most industrial uses."
building-driving-school = Driving school
    .summary = Train inhabitants to drive better
    .description = Train inhabitants to drive better.
building-stadium = Stadium
    .summary = Inhabitants can exercise here
    .description = "Inhabitants do exercise here, recovering happiness and improve athletic skills."
building-prison = Prison
    .summary = Correctional services for criminals
    .description = Inhabitants with negative satisfaction are imprisoned here to recultivate morality and restore satisfaction.
building-customs = Customs
    .summary = Disallow outlaws from intrusion
    .description = Customs is a security checkpoint at which operators check all inhabitants passing through. Surround important buildings with customs so that outlaws cannot grief them.

building-cats-population = Population
    .description = Buildings to support inhabitant population
building-cats-traffic = Traffic
    .description = Buildings for traffic control
building-cats-electricity = Electricity
    .description = Buildings to manage electricity
building-cats-storage = Storage
    .description = Buildings to store resources
building-cats-industrial = Industrial
    .description = Buildings for processing intermediates
building-cats-education = Education
    .description = Buildings to train inhabitant skills
building-cats-entertainment = Entertainment
    .description = Buildings to restore happiness
building-cats-security = Security
    .description = Buildings related to crimes

crime-pickpocket = Pickpocket
    .description = Steal cargo carried by other inhabitants
crime-robbery = Robbery
    .description = Rob a building and remove the cargo stored inside
crime-arson = Arson
    .description = Set a building on fire
