[package]
name = "traffloat-base"
description = "Traffloat base components"
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}
repository = {workspace = true}
authors = {workspace = true}
version = {workspace = true}
rust-version = {workspace = true}

[dependencies]
bevy = {workspace = true}
prost = {workspace = true}
prost-types = {workspace = true}
serde = "1.0.204"

[build-dependencies]
anyhow = "1.0.86"
prost-build = {workspace = true}
traffloat-build-boilerplate = {workspace = true}
