[[init]]
type = "Edge"
alpha = "core"
beta = "terminal-core-hut"
radius = 0.1

	[init.hitpoint]
	current = 100.0
	max = 100.0

	[[init.ducts]]
	center = [0.0, 0.0]
	radius = 0.01

		[init.ducts.ty]
		type = "Liquid"
		direction = "AlphaToBeta"
		alpha_storage = "reservoir0"
		beta_storage = "buffer0"

	[[init.ducts]]
	center = [0.02, 0.05]
	radius = 0.01

		[init.ducts.ty]
		type = "Electricity"
