[[def]]
type = "Building"
id = "driving-school"
category = "education"
hitpoint = 150.0
name = {src = "main", key = "building-driving-school"}
summary = {src = "main", key = "building-driving-school-summary"}
description = {src = "main", key = "building-driving-school-description"}

	[[def.shapes]]
	unit = "Cube"
	texture = {src = "buildings", name = "driving-school"}

	[def.storage]
	cargo = 1000.0
	gas = 1000.0

		[[def.storage.liquid]]
		id = "buffer0"
		capacity = 10.0
		name = {src = "main", key = "storage-liquid-generic-buffer"}

		[[def.storage.population]]
		id = "teacher"
		capacity = 1
		name = {src = "main", key = "storage-population-school-teacher"}

		[[def.storage.population]]
		id = "student"
		capacity = 4
		name = {src = "main", key = "storage-population-school-student"}

	[[def.features]]
	type = "Reaction"
	title = {src = "main", key = "reaction-driving-lesson"}
	description = {src = "main", key = "reaction-driving-lesson-description"}

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Skill"
			ty = "driving-skill"
			levels = {start = 10.0, end = 20.0}
			storage = "teacher"

			[def.features.catalysts.multipliers]
			underflow = 0.0
			min = 0.0
			max = 1.0
			overflow = 1.0

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Skill"
			ty = "teaching-skill"
			levels = {start = 0.0, end = 20.0}
			storage = "teacher"

			[def.features.catalysts.multipliers]
			underflow = 1.0
			min = 1.0
			max = 2.0
			overflow = 2.0

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Skill"
			ty = "driving-skill"
			levels = {start = 0.0, end = 20.0}
			storage = "student"

			[def.features.catalysts.multipliers]
			underflow = 1.0
			min = 1.0
			max = 0.0
			overflow = 0.0

		[[def.features.puts]]
		type = "Skill"
		ty = "driving-skill"
		base = 0.03
		storage = "student"

		[def.features.policy]
		configurable = false
		on_underflow = {type = "ReduceRate"}
		on_overflow = {type = "ReduceRate"}
