[[def]]
type = "Building"
id = "filtration-plant"
category = "industrial"
hitpoint = 150.0
name = {src = "main", key = "building-filtration-plant"}
summary = {src = "main", key = "building-filtration-plant-summary"}
description = {src = "main", key = "building-filtration-plant-description"}

	[[def.shapes]]
	unit = "Cube"
	texture = {src = "buildings", name = "filtration-plant"}

	[def.storage]
	cargo = 3000.0
	gas = 1000.0

		[[def.storage.liquid]]
		id = "input"
		capacity = 1000.0
		name = {src = "main", key = "storage-liquid-factory-input"}

		[[def.storage.liquid]]
		id = "output"
		capacity = 1000.0
		name = {src = "main", key = "storage-liquid-factory-output"}

		[[def.storage.population]]
		id = "operator"
		capacity = 1
		name = {src = "main", key = "storage-population-generic-operator"}

	[[def.features]]
	type = "Reaction"
	title = {src = "main", key = "reaction-asteroidal-water-filtration"}
	description = {src = "main", key = "reaction-asteroidal-water-filtration-description"}

		[[def.features.catalysts]]
			[def.features.catalysts.range]
			type = "Skill"
			ty = "mechanic-skill"
			levels = {start = 0.0, end = 20.0}
			storage = "operator"

			[def.features.catalysts.multipliers]
			underflow = 1.0
			min = 1.0
			max = 2.0
			overflow = 2.0

		[[def.features.puts]]
		type = "Liquid"
		ty = "asteroidal-water"
		base = -100.0
		storage = "input"

		[[def.features.puts]]
		type = "Liquid"
		ty = "filtered-water"
		base = 100.0
		storage = "output"

		[[def.features.puts]]
		type = "Cargo"
		ty = "rock"
		base = 10.0

		[[def.features.puts]]
		type = "Cargo"
		ty = "sediment"
		base = 10.0

		[def.features.policy]
		configurable = true
		on_underflow = {type = "ReduceRate"}
		on_overflow = {type = "ReduceRate"}
