[[def]]
type = "Building"
id = "terminal"
category = "traffic"
hitpoint = 100.0
name = {src = "main", key = "building-terminal"}
summary = {src = "main", key = "building-terminal.summary"}
description = {src = "main", key = "building-terminal.description"}

	[[def.features]]
	type = "RailPump"
	force = 100.0

	[[def.features]]
	type = "LiquidPump"
	force = 100.0

	[[def.features]]
	type = "GasPump"
	force = 100.0

	[[def.shapes]]
	unit = "Cube"
	texture = {src = "buildings", name = "terminal"}

		[[def.shapes.transform]]
		type = "Scale"
		x = 0.2
		y = 0.2
		z = 0.2

	[def.storage]
	cargo = 1000.0
	gas = 1000.0

		[[def.storage.liquid]]
		capacity = 10.0
		name = {src = "main", key = "storage-liquid-generic-buffer"}

		[[def.storage.liquid]]
		capacity = 10.0
		name = {src = "main", key = "storage-liquid-generic-buffer"}

		[[def.storage.liquid]]
		capacity = 10.0
		name = {src = "main", key = "storage-liquid-generic-buffer"}

		[[def.storage.liquid]]
		capacity = 10.0
		name = {src = "main", key = "storage-liquid-generic-buffer"}

		[[def.storage.population]]
		building = 8
		name = {src = "main", key = "storage-population-generic-transit"}
