name: Client build
on:
  push:
    branches:
      - master
      - imperative-saves
    tags:
      - "*"
jobs:
  build:
    name: "Web client build"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-09
          profile: default
          default: true
          target: wasm32-unknown-unknown
      - name: Cache cargo tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: trunk-just-10-09
      - run: test -f ~/.cargo/bin/just || cargo install trunk just

      - name: Install toolchain dependencies
        run: just deps
      - name: Build web client
        run: just client-build /$(echo ${{github.ref}} | cut -d/ -f3)

      - name: Set Git author
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Clone site repo
        uses: actions/checkout@v2
        with:
          repository: traffloat/traffloat.github.io
          ssh-key: ${{secrets.SITE_KEY}}
          path: .site-repo
      - name: Delete previous build
        run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
        working-directory: .site-repo
      - name: Copy artifact to site repo
        run: cp -r client/dist .site-repo/$(echo ${{github.ref}} | cut -d/ -f3)
      - name: Git commit
        run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit --allow-empty -m "WASM client build for traffloat/traffloat@${{github.sha}}"
        working-directory: .site-repo
      - name: Push pages
        run: git push
        working-directory: .site-repo
