[package]
name = "traffloat-desktop"
description = "Traffloat desktop client"
homepage = {workspace = true}
license = {workspace = true}
edition = {workspace = true}
repository = {workspace = true}
authors = {workspace = true}
version = {workspace = true}
rust-version = {workspace = true}

[dependencies]
bevy = {workspace = true}
traffloat-graph = {workspace = true}
traffloat-base = {workspace = true}
derive_more = "0.99.17"
typed-builder = "0.18.2"
smallvec = "1.13.2"
