[package]
name = "traffloat-desktop"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2021"
repository = "https://github.com/traffloat/traffloat"
homepage = "https://github.com/traffloat/traffloat"
description = "Traffloat desktop client"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
derive-new = "0.5.9"
futures = "0.3.19"
log = "0.4.14"
pretty_env_logger = "0.4.0"
three-d = "0.11.1"
tokio = {version = "1.15.0", features = ["fs", "macros", "rt-multi-thread"]}
traffloat-client = {version = "0.2.0", path = "../client"}
traffloat-def = {version = "0.2.0", path = "../def"}
traffloat-types = {version = "0.2.0", path = "../types"}
